version: "3.8"
services:
  db:
    image: postgres
    hostname: db
    restart: always
    environment:
      POSTGRES_PASSWORD: whatever
      POSTGRES_DB: promote_it_on_abrys_fam
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data
  bot:
    build:
      context: .
      dockerfile: local.Dockerfile
    depends_on:
      - db
