name: Prod Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          # TODO: do this with oidc: https://aws.amazon.com/blogs/security/use-iam-roles-to-connect-github-actions-to-actions-in-aws/
          #   role-to-assume: arn:aws:iam::123456789012:role/role-name
          #   oidc-provider: https://token.actions.githubusercontent.com

      - name: Install PNPM
        run: npm install -g pnpm
      - name: Install Dependencies
        run: pnpm install

      - name: Deploy to AWS
        run: pnpm sst deploy --stage prod
